domains:
  - domain: shark-app-kki.doserverless-dev3.io
    type: PRIMARY
    zone: doserverless-dev3.io
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: supabase-app-2
    match:
      authority:
        exact: ""
      path:
        prefix: /
name: shark-app-kki
region: blr
static_sites:
- build_command: npm install & npm run build
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: ksai7991/supabase-app-2
  name: supabase-app-2
  source_dir: /
